repos:
  - repo: local
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromissing Python code formatter"
        entry:  black
        language: python
        require_serial: true
        types_or:  [python, pyi]